### ISSUE TITLE
#10005 : Note View 관련 기능 요청

### ISSUE THREAD

**Issue by owneul-k** [Jason0803/Cocoa-Note#11]
> NoteViewController 수정
- command = "noteView"

> Fields
- String id : Session memberVO
- boolean isCurr : param (true / false)
( - int diaryNo : param )

> Description : 
isCurr 파라미터값이 true일 때에는 해당 사용자의 전체 노트리스트(attribute name: notes)와 해당 사용자가 가장 최근 수정한 노트(attribute name: note)를,
isCurr 파라미터값이 false일 때에는 해당 사용자의 전체 노트리스트(attribute name: notes)와 해당 사용자가 요청한 diaryNo 노트(attribute name: note)를 받는 기능이 필요합니다!!

> Heading_to : note_view.jsp

**Comment by Jason0803** [comment]
@qazwsx2800 민영씨 오후 세시 이전 완료 바랍니다 ~
- 리뷰 / 테스트 필요하므로

**Comment by qazwsx2800** [comment]
@owneul-k #00102 COMMIT함

**Comment by chocemp** [comment]
note 전체 list가 세팅되지 않는데 확인부탁드려요~~

**Comment by owneul-k** [comment]
@qazwsx2800 
Bug at  NoteViewController

[system log] : getCurrDiaryNo() : 19
[system log] : getNoteByNo() : Note [title=null, currentDate=null]
isCurr 파라미터값이 true일 때 가장 최근 수정한 노트(attribute name: note)를 받아오는 과정에서 getCurrDiaryNo() 메소드가 가장 최근 수정한 노트 번호를 받아오는 기능을 수행하지 못함.
-> 가장 최근 작성한 Diary의 no를 받아오고 있음. (Memo일수도 있고 Schedule일수도 있습니다)
가장 최근 수정한(최근 작성이 아니에요!) Note의 no를 받아오는 기능을 별도로 구현해야 할 것 같습니다.
