### ISSUE TITLE
#10006 NoteView 플로우 관련

### ISSUE THREAD

**Issue by chocemp** [Jason0803/Cocoa-Note#12]
> NoteViewController.java
- command = "noteView"
> WriteNoteController
- command = "writeNote"
> UpdateNoteController
- command = "updateNote"

> Description : 
새 노트 작성이나 기존 노트 수정시 각각 WriteNoteController, UpdateNoteController에서 NoteViewController로 포워딩되었으면 좋겠습니다(방금 작성/수정한 노트 볼 수 있게)

> Heading_to : note_view.jsp

**Comment by Jason0803** [comment]
#00107 commit 으로 해소되었으므로 close 합니다.
