### ISSUE TITLE
#10007 : Register > '이미존재하는  ID ' 에서 칸 넘음

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#15]
@InhoAndrewJung  님,

-Issue : Register > '이미존재하는  ID ' 에서 칸 넘음
-Steps to REPRO : 
1. register.jsp 에서 로그인 정보를 기존 가입된 계정 정보 이용하여 입력

<img width="1175" alt="screen shot 2017-10-23 at 4 07 10 pm" src="https://user-images.githubusercontent.com/8012906/31876177-614714e0-b80c-11e7-9cf3-2888fbe44bd6.png">

**Comment by Jason0803** [comment]
@InhoAndrewJung 본 이슈 해소 확인 되면 close 부탁드립니다 ~

**Comment by InhoAndrewJung** [comment]
#00184 : 완료
