### ISSUE TITLE
홈페이지 타이틀이 '코코아노트'가 아니라 '카카오노트'로 나와요

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#23]
<img width="427" alt="screen shot 2017-10-25 at 1 44 27 pm" src="https://user-images.githubusercontent.com/8012906/31980902-a6edcb04-b98a-11e7-96bc-d4b416814bc3.png">

**Comment by InhoAndrewJung** [comment]
접수완료

**Comment by InhoAndrewJung** [comment]
해당 부분 발견 못함.  어디지? ㅇㅅㅇ..

**Comment by InhoAndrewJung** [comment]
없음. 확인완료
