### ISSUE TITLE
[Front-end] 어느 페이지를가도 페이지 타이틀에 '코코아노트' 혹은 '메모보기' 등 으로 나오게 변경 요청

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#26]
어느 페이지를가도 페이지 타이틀에 '코코아노트' 혹은 '메모보기' 등 으로 나오게 해주세용
> 현재 몇몇 페이지는 타이틀에 커맨드가 포함이 됩니당 고정 가능하다네요

**Comment by InhoAndrewJung** [comment]
접수완료

**Comment by InhoAndrewJung** [comment]
수정중인 페이지(eg. cal_view.jsp) 제외하고 처리완료

#00203 : add title
