### ISSUE TITLE
[Front-end] 유저 이름 칸이 nav bar 넘는 이슈

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#27]
Test Environment 
- Safari
- master branch (2017.10.26 9:20 am)

<img width="1223" alt="screen shot 2017-10-26 at 9 16 53 am" src="https://user-images.githubusercontent.com/8012906/32029343-db87a534-ba2e-11e7-8a78-d372d5071f62.png">

**Comment by InhoAndrewJung** [comment]
접수완료
