### ISSUE TITLE
[Back-end] DAO 날짜관련

### ISSUE THREAD

**Issue by owneul-k** [Jason0803/Cocoa-Note#32]
> Description : 
날짜를 다루는 로직에서 hour와 minute도 다루고 싶습니다~!
ResultSet에 접근할때 getDate() -> getTimestamp()로 변경 요청드려요

**Comment by Neozuni** [comment]
#00201:  getDate() -> getTimestamp()
DiaryDAO 에서 수정작업 완료 하였습니다.
getDate() -> getTimestamp()로 변경
