### ISSUE TITLE
검색 결과 데이터 raw 하게 나옴 > presentation 방법 변경 필요

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#35]
검색 결과 데이터 raw 하게 나옴 > presentation 방법 변경 필요 (첨부 이미지 참조)

<img width="1148" alt="screen shot 2017-10-27 at 11 28 22 am" src="https://user-images.githubusercontent.com/8012906/32085504-6cffe4c8-bb0a-11e7-9dff-d940a8314779.png">

**Comment by InhoAndrewJung** [comment]
해결완료
