### ISSUE TITLE
쓰기, 수정 등 버튼 동작 시 연속 수행 안되게 제어 필요

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#36]
쓰기, 수정 등 버튼 동작 시 연속 수행 안되게 제어 필요

**Comment by InhoAndrewJung** [comment]
접수완료

**Comment by Jason0803** [comment]
현재 방식은 불필요한 클릭이 한번 더 들어갑니다.
논의 후,  일단은 시연때엔 revert 하거나 개선이 필요한것으로 보입니다
