### ISSUE TITLE
calView 물결 좀 어떻게 해주세요

### ISSUE THREAD

**Issue by chocemp** [Jason0803/Cocoa-Note#40]
![default](https://user-images.githubusercontent.com/32825786/32093071-fb1ca84c-bb35-11e7-8249-846c553ba600.jpg)

이거 물결표시좀 어떻게 바꿔요 정인호 UI 매니저님

**Comment by InhoAndrewJung** [comment]
고객님, 당황하셨나요?
물결 구데기 어떻게 바꿔드렸어요  \\^.^//
