### ISSUE TITLE
Schedule title에 공백이 있을 때, 한 단어만 입력할 경우 검색 안됨

### ISSUE THREAD

**Issue by InhoAndrewJung** [Jason0803/Cocoa-Note#46]
> 예시
- 일정 제목 : thursday party
-검색시도 1: thrusday -> 검색안됨
-검색시도 2: party-> 검색안됨
-검색시도 3: thrusday party -> 검색됨

시간되면 개선부탁해요 :)

**Comment by Jason0803** [comment]
이런건 초반에 컨셉을 지정 해주시거나, 이 개선이 적합한지 여부도 고려한 내용을 포함하여 보내주시기 바랍니다.
이 개선점이 불가능한 이유를 말씀 드리자면

> 우선 예로 전달주신 케이스 경우, '목요일 파티' 라는 내용의 일정을 검색하고싶은데,
> 전혀 다른 이미 지난 혹은 원치않는 다른 '파티' 라는 내용이 포함된 모든 스케쥴과 노트/메모 를 불러오는것이 맞을까요 ?

노트 혹은 메모에 언젠가 작성한 내용을 검색할 때
**Case 1.**
목적 : <차 종류들에 대해서 작성했던것 찾고싶다>
검색어 : '차량 종류'
위와같은 케이스에선 예상 검색결과 중에서,
- '...도로가 막힐땐 [차량]이 너무 많은것이 특징이다.'
라는 결과도 나올 수 있는데 적합할까요?

원하신다면 바로 적용 가능하도록 구현은 해뒀으나 ,"thursday party"보다 더 적합한 예시 case가 있거나,
 저런 케이스 조정하는 방법 (하단 수도코드 참조) 등을 통해서 원한다면 하겠지만
논리적으로 맞지 않는것 같습니다.

```
..
// keyword : 입력값. keywords : 공백포함시 단어별 나눠줌
if(keyword.contains(" ") {
// 1. 전체가 포함된것이 있을 경우
 String[] keywords = keyword.split(",")l
 // 노트검색 (keyword)
if(note.contains(keyword) --> return
 // 메모검색 (keyword)
if(memo.contains(keyword) --> return
 // 스케쥴검색 (keyword)
if(schedule.contais(keyword) --> return

} else {
// 2. 전체가 포함된것이 없을 경우 (현재 알고리즘과 동일)
 for(String word : keywords) {
 // 노트검색 (word)
if(note.contains(word) --> return
 // 메모검색 (word)
if(memo.contains(word) --> return
 // 스케쥴검색 (word)
if(schedule.contais(keyword) --> return
}
..
```
