### ISSUE TITLE
[beta-1] 더블클릭 해야만 새로운 노트/일정 추가 등 가능한 이슈

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#51]
현재 #37 이슈 해소를 위해 걸어둔 스크립트 영향으로 보임.

Steps to REPRO : 

1. 로그인
2. 노트/일정 등 작성 페이지 이동
3. 우측 상단 + 버튼 클릭

Expected Result : 1회클릭으로 새로운 노트/스케쥴 작성 창으로 전환되어야 함
Actual Result : 2회 클릭 필요.

우선 시연때만 해당 기능 풀어두고, 이후 개선 때 새로운 대안에 대해 논의 해보는것이 어떨까요 ?

**Comment by InhoAndrewJung** [comment]
확인 결과 1회 클릭만으로 전환됨.
delay가 1초로 설정되어 조금 기다려야함.

한 번 서버 재시작하고, 시크릿 페이지에서 해볼래? 적용안되었을 수도..

**Comment by Jason0803** [comment]
@InhoAndrewJung  헉..바꼈었나 보네용 ㅠ_ㅠ 나중에 확인후 close 할게요 !
