### ISSUE TITLE
#10003 : Branch 정리

### ISSUE THREAD

**Issue by Jason0803** [Jason0803/Cocoa-Note#8]
- 다쓴 브랜치 코멘트 남겨주시면 정리 (delete) 하겠습니다.
--> 각자 로컬엔 남습니다

- 새로운 작업이나 다른 로직땐 꼭 브랜치 나누는 습관 !

**Comment by qazwsx2800** [comment]
controllerminyoung 삭제해주세염

**Comment by InhoAndrewJung** [comment]
UI/UX-1025
UI/UX-1026
삭제 ㄱㄱ
